apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: lpd-default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default # Namespace where the deployment will be installed.
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
